#!/bin/bash

CONTAINER_USERNAME=$USER
CONTAINER_GROUPNAME=$(id -g -n)
GROUP_ID=$(id -g)
USER_ID=$(id -u)
DOCKER_HOSTNAME=`hostname`-docker
HOMEDIR_IN_DOCKER='/home/'$CONTAINER_USERNAME
DOCKERIMAGE=debian:jessie

echo $DOCKER_HOSTNAME

docker run -i -t --rm -v "$HOME:$HOMEDIR_IN_DOCKER"  \
	-w "/home/$CONTAINER_USERNAME" \
	-h $DOCKER_HOSTNAME  \
	$DOCKERIMAGE  \
	$HOMEDIR_IN_DOCKER/docker_entry.sh $CONTAINER_USERNAME $CONTAINER_GROUPNAME $GROUP_ID $USER_ID

